// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrackNowApi.Model
{
    public partial class CustomerFilingTrackingNotifications
    {
        
        public decimal FileTrackingId { get; set; }
        public decimal? NotifiedUserId { get; set; }
        public string? NotificationFrom { get; set; }
        public string? NotificationTo { get; set; }
        public string? NotificationCC { get; set; }
        public string? NotificationSubject { get; set; }
        public string? NotificationType { get; set; }
        public string? NotificationText { get; set; }
        public bool? InformationRead { get; set; }
        public bool? InformationDeleted { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CreateUser { get; set; }
        [ConcurrencyCheck]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal NotificationId { get; set; }
    }
}