// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrackNowApi.Model
{
    public partial class CustomerApprovalStatus
    {
        public decimal? WorkflowId { get; set; }
        public string ApproverName { get; set; }
        public string AlternateApprovers { get; set; }
        public string Comments { get; set; }
        public string Attachments { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string DoneBy { get; set; }
        public DateTime? DoneOn { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal CustomerApprovalId { get; set; }
    }
}